stof_doctrine_extensions:
  default_locale: fr_FR
  orm:
    default:
      timestampable: true


sylius_resource:
  resources:
    aropixel.block:
      driver: doctrine/orm
      classes:
        model: Aropixel\SyliusBlockPlugin\Entity\Block
        form: Aropixel\SyliusBlockPlugin\Form\Type\BlockType

    aropixel.block_category:
      driver: doctrine/orm
      classes:
        model: Aropixel\SyliusBlockPlugin\Entity\BlockCategory


sylius_grid:
  grids:
    aropixel_admin_block:
      driver:
        name: doctrine/orm
        options:
          class: Aropixel\SyliusBlockPlugin\Entity\Block
      fields:
        title:
          type: string
          label: aropixel.ui.block.title
        category.title:
          type: string
          label: aropixel.ui.block_category.title
        enabled:
          type: twig
          label: sylius.ui.enabled
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete

    aropixel_admin_block_category:
      driver:
        name: doctrine/orm
        options:
          class: Aropixel\SyliusBlockPlugin\Entity\BlockCategory
      fields:
        title:
          type: string
          label: aropixel.ui.block_category.title
        enabled:
          type: twig
          label: sylius.ui.enabled
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete

fos_ck_editor:
  configs:
    main_config:
      toolbar:
        - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Table', '-', 'Styles', 'Format','Font','FontSize', '-', 'TextColor', 'BGColor', 'Source'] }
      filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: []

fm_elfinder:
  #assets_path: / # default is /assets, this is where css/js elfinder files are
  instances:
    default:
      locale: '%locale%' # defaults to current request locale
      editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
      relative_path: false #default true, will produce absolute urls to specified file(s)
      #editor_template: custom template for your editor # default null
      #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
      #fullscreen: true|false # default is true, applies to simple and ckeditor editors
      #theme: smoothness # jquery theme, default is 'smoothness'
      #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
      connector:
        #debug: true|false # defaults to false
        roots:       # at least one root must be defined, defines root filemanager directories
          uploads:
            #show_hidden: true|false # defaults to false, hides dotfiles
            driver: LocalFileSystem
            path: uploads
            upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
            upload_deny: ['all']
            upload_max_size: 2M # also file upload sizes restricted in php.ini
            #attributes: example of setting attributes permission
            #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
